# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSnag < Formula
  desc "A TUI to snag your dead git worktrees"
  homepage "https://github.com/kurabuchi-kentaro/git-snag"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.2/git-snag_0.1.2_darwin_amd64.tar.gz"
      sha256 "5c64de4251ea920c006aed95cb9d6923d3f8c09102a09c35bc4d68879627d32d"

      define_method(:install) do
        bin.install "git-snag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.2/git-snag_0.1.2_darwin_arm64.tar.gz"
      sha256 "d8fc5c6a6523b72b4b50489745a7f80c9ef61f7fd796d9516f6cac096c5b3ab4"

      define_method(:install) do
        bin.install "git-snag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.2/git-snag_0.1.2_linux_amd64.tar.gz"
      sha256 "18eaca0140f539595a1d6dba8575fae0d342a0361c0173be55443c2fcbbe22ec"
      define_method(:install) do
        bin.install "git-snag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.2/git-snag_0.1.2_linux_arm64.tar.gz"
      sha256 "9f85031dd9f7df9b5e660e30236071945eebefbfbf6b62fe5b60f5c4cb156a2c"
      define_method(:install) do
        bin.install "git-snag"
      end
    end
  end

  def caveats
    <<~EOS
      git-snag's status tags use Nerd Font glyphs by default. If your
      terminal font isn't patched, install one from https://www.nerdfonts.com
      and set it in your terminal.

      No Nerd Font? Fall back to plain Unicode glyphs, either per run:
        git-snag --icons unicode
      or permanently in ~/.config/git-snag/config.yaml:
        ui:
          icons: unicode
    EOS
  end

  test do
    system "#{bin}/git-snag", "--version"
  end
end
