# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSnag < Formula
  desc "A TUI to snag your dead git worktrees"
  homepage "https://github.com/kurabuchi-kentaro/git-snag"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.0/git-snag_0.1.0_darwin_amd64.tar.gz"
      sha256 "2940919c7f22bbae4e8fad8dea21644117c61b817b27fa175b9d0f1bd7d339d6"

      define_method(:install) do
        bin.install "git-snag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.0/git-snag_0.1.0_darwin_arm64.tar.gz"
      sha256 "07a86f4df2a2fdaac9a31c59c15dc9083728dc731fff8d00b38003b3b36a46af"

      define_method(:install) do
        bin.install "git-snag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.0/git-snag_0.1.0_linux_amd64.tar.gz"
      sha256 "94e90bafa6bb51abe362c5f74a56bc39b1f5a34c57c39c233d7b13c0fca4bb82"
      define_method(:install) do
        bin.install "git-snag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurabuchi-kentaro/git-snag/releases/download/v0.1.0/git-snag_0.1.0_linux_arm64.tar.gz"
      sha256 "00f0749ca6beab45acfeb3ef6029cb9905d8ff3026866fcddc42c109b604909e"
      define_method(:install) do
        bin.install "git-snag"
      end
    end
  end

  test do
    system "#{bin}/git-snag", "--version"
  end
end
